name = "FNCFunctions"
uuid = "ab0dfefa-d313-416d-841c-e73335ae36c8"
authors = ["Toby Driscoll <driscoll@udel.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1.11.0"
OrdinaryDiffEq = "6.90.1"
Polynomials = "4.0.12"
SparseArrays = "1.11.0"
julia = "1"
